from __future__ import annotations

import shutil
import subprocess
from pathlib import Path

import pytest

FFMPEG = shutil.which("ffmpeg")


@pytest.fixture(scope="session")
def opus_fixture(tmp_path_factory: pytest.TempPathFactory) -> Path:
    """A 1.2 s opus voice-note-like file (ogg/opus, like WhatsApp), generated by ffmpeg."""
    if FFMPEG is None:
        pytest.skip("ffmpeg not installed")
    path = tmp_path_factory.mktemp("fixtures") / "note.opus"
    subprocess.run(
        [
            FFMPEG, "-hide_banner", "-nostdin", "-y",
            "-f", "lavfi", "-i", "sine=frequency=440:duration=1.2:sample_rate=48000",
            "-c:a", "libopus", "-b:a", "24k", "-ac", "1",
            str(path),
        ],
        check=True,
        capture_output=True,
    )
    return path
